### ISSUE TITLE
Coverage merger should not fail when additional fields are present

### ISSUE THREAD

**Issue by DreierF** [dpagano/closure-coverage-merger#1]
Since we use an additional field inside the closure coverage format to document which test produced the coverage contained in the file, the coverage merger complains about the file having a wrong format. IMHO it should only fail if some required fields are missing, but additional ones should be ok or only produce a warning.
```
Error: Wrong format of coverage in .../coverage-856910907.json
at ClosureCoverageMerger.error (closure-coverage-merger.js:107:9)
at ClosureCoverageMerger.checkCoverage (coverage-merger.js:54:9)
at inputFileNames.forEach.fileName (coverage-merger.js:45:9)
at Array.forEach (<anonymous>)
at ClosureCoverageMerger.parseFiles (coverage-merger.js:43:18)
at ClosureCoverageMerger.mergeCoverage (coverage-merger.js:37:8)
at readArgumentsAndMergeCoverage (closure-coverage-merger/lib/index.js:47:9)
at Object.<anonymous> (closure-coverage-merger/lib/index.js:50:1)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
```

**Comment by dpagano** [comment]
I agree. Do you want to make the changes?

**Comment by DreierF** [comment]
I'll try it after vacation 😉
